apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    path: ./argocd
    chart: max-chart
    repoURL: https://github.com/maxxam123/helm.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - ./values.yaml
  destination:
    name: https://kubernetes.default.svc
    namespace: max2
  syncPolicy:
    automated: {}
