apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    path: argocd
    chart: max-chart
    repoURL: https://github.com/maxxam123/helm.git
    targetRevision: v0.1.0
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: in-cluster
    namespace: max2
  syncPolicy:
    automated: {}
