kind: Application
metadata:
  name: test-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocd
  syncPolicy:
    automated:
      prune: true
  source:
    path: argocd
    repoURL: https://github.com/maxxam123/helm.git
    targetRevision: 1.16.0
    helm:
      valueFiles:
      - values.yaml
