apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    chart: max-chart
    repoURL: https://github.com/maxxam123/helm.git
    targetRevision: v0.1.0
    # helm:
      # releaseName: cert-manager
  destination:
    name: in-cluster
    namespace: max2
  syncPolicy:
    automated: {}
